/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -v -c AccountManagerProxy -p client/account_manager_proxy.h:client/account_manager_proxy.cpp -i ../dbus/dbus_helper.h org.saruneko.tori.account_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "client/account_manager_proxy.h"

/*
 * Implementation of interface class AccountManagerProxy
 */

AccountManagerProxy::AccountManagerProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

AccountManagerProxy::~AccountManagerProxy()
{
}
