/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ToriDBusAdaptor -a tori_dbus_adaptor.h:tori_dbus_adaptor.cpp com.saruneko.tori.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "tori_dbus_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ToriDBusAdaptor
 */

ToriDBusAdaptor::ToriDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ToriDBusAdaptor::~ToriDBusAdaptor()
{
    // destructor
}

void ToriDBusAdaptor::authenticate(uint accountId)
{
    // handle method call com.saruneko.tori.authenticate
    QMetaObject::invokeMethod(parent(), "authenticate", Q_ARG(uint, accountId));
}

QVariantMap ToriDBusAdaptor::getAccounts()
{
    // handle method call com.saruneko.tori.getAccounts
    QVariantMap accountId;
    QMetaObject::invokeMethod(parent(), "getAccounts", Q_RETURN_ARG(QVariantMap, accountId));
    return accountId;
}

void ToriDBusAdaptor::setPin(const QString &pin, uint accountId)
{
    // handle method call com.saruneko.tori.setPin
    QMetaObject::invokeMethod(parent(), "setPin", Q_ARG(QString, pin), Q_ARG(uint, accountId));
}

