/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c TodiDBusDaemon -a tori_dbus_daemon.h:tori_dbus_daemon.cpp com.saruneko.tori.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "tori_dbus_daemon.h"

ToriDBusDaemon::ToriDBusDaemon(QObject *parent)
    : QObject(parent)
{
    _man = new AccountManager();
}

QVariantMap ToriDBusDaemon::getAccounts()
{
    return _man->getAccounts();
}

void ToriDBusDaemon::authenticate(uint accountId)
{
}

void ToriDBusDaemon::setPin(const QString &pin, uint accountId)
{
    emit pinReceived(pin, accountId);
}

void ToriDBusDaemon::emitOAuthPinUrl(const QString &pinUrl, uint accountId, const QString &username)
{
    emit oauthPinUrl(pinUrl, accountId, username);
}

void ToriDBusDaemon::emitAuthenticated(uint accountId, QString &username)
{
    emit authenticated(accountId, username);
}

