/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c AccountManagerAdaptor -a core/account_manager_adaptor.h:core/account_manager_adaptor.cpp -i dbus/dbus_helper.h org.saruneko.tori.account_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "core/account_manager_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AccountManagerAdaptor
 */

AccountManagerAdaptor::AccountManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AccountManagerAdaptor::~AccountManagerAdaptor()
{
    // destructor
}

DBusObjectPathHash AccountManagerAdaptor::getAccounts()
{
    // handle method call org.saruneko.tori.AccountManager.getAccounts
    DBusObjectPathHash accounts;
    QMetaObject::invokeMethod(parent(), "getAccounts", Q_RETURN_ARG(DBusObjectPathHash, accounts));
    return accounts;
}

