/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c AccountManagerAdaptor -a core/account_manager_adaptor.h:core/account_manager_adaptor.cpp org.saruneko.tori.account_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "core/account_manager_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AccountManagerAdaptor
 */

AccountManagerAdaptor::AccountManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AccountManagerAdaptor::~AccountManagerAdaptor()
{
    // destructor
}

void AccountManagerAdaptor::authenticate(uint accountId)
{
    // handle method call com.saruneko.tori.authenticate
    QMetaObject::invokeMethod(parent(), "authenticate", Q_ARG(uint, accountId));
}

QVariantMap AccountManagerAdaptor::getAccounts()
{
    // handle method call com.saruneko.tori.getAccounts
    QVariantMap accountId;
    QMetaObject::invokeMethod(parent(), "getAccounts", Q_RETURN_ARG(QVariantMap, accountId));
    return accountId;
}

void AccountManagerAdaptor::setPin(const QString &pin, uint accountId)
{
    // handle method call com.saruneko.tori.setPin
    QMetaObject::invokeMethod(parent(), "setPin", Q_ARG(QString, pin), Q_ARG(uint, accountId));
}

