/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c AccountManagerAdaptor -a core/account_manager_adaptor.h:core/account_manager_adaptor.cpp -i dbus/dbus_helper.h org.saruneko.tori.account_manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACCOUNT_MANAGER_ADAPTOR_H_1357565404
#define ACCOUNT_MANAGER_ADAPTOR_H_1357565404

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbus/dbus_helper.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.saruneko.tori.AccountManager
 */
class AccountManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.saruneko.tori.AccountManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.saruneko.tori.AccountManager\">\n"
"    <method name=\"getAccounts\">\n"
"      <annotation value=\"DBusObjectPathHash\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"out\" type=\"a{so}\" name=\"accounts\"/>\n"
"    </method>\n"
"    <signal name=\"accountCreated\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"accountId\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"accountName\"/>\n"
"    </signal>\n"
"    <signal name=\"accountUpdated\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"accountId\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"accountName\"/>\n"
"    </signal>\n"
"    <signal name=\"accountDeleted\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"accountId\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"accountName\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    AccountManagerAdaptor(QObject *parent);
    virtual ~AccountManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    DBusObjectPathHash getAccounts();
Q_SIGNALS: // SIGNALS
    void accountCreated(uint accountId, const QString &accountName);
    void accountDeleted(uint accountId, const QString &accountName);
    void accountUpdated(uint accountId, const QString &accountName);
};

#endif
