/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c AccountAdaptor -a core/account_adaptor.h:core/account_adaptor.cpp org.saruneko.tori.account.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACCOUNT_ADAPTOR_H_1358804038
#define ACCOUNT_ADAPTOR_H_1358804038

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.saruneko.tori.Account
 */
class AccountAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.saruneko.tori.Account")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.saruneko.tori.Account\">\n"
"    <signal name=\"authenticationError\">\n"
"      <arg direction=\"out\" type=\"u\" name=\"error\"/>\n"
"    </signal>\n"
"    <!-- status API -->\n"
"    <method name=\"retweets\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"tweet_id\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"    </method>\n"
"    <method name=\"show\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"tweet_id\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"    </method>\n"
"    <method name=\"destroy\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"tweet_id\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"    </method>\n"
"    <method name=\"update\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"status\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"    </method>\n"
"    <method name=\"retweet\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"tweet_id\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"options\"/>\n"
"    </method>\n"
"    <!-- status API signals -->\n"
"  </interface>\n"
        "")
public:
    AccountAdaptor(QObject *parent);
    virtual ~AccountAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void destroy(const QString &uuid, uint tweet_id, const QVariantMap &options);
    void retweet(const QString &uuid, uint tweet_id, const QVariantMap &options);
    void retweets(const QString &uuid, uint tweet_id, const QVariantMap &options);
    void show(const QString &uuid, uint tweet_id, const QVariantMap &options);
    void update(const QString &uuid, const QString &status, const QVariantMap &options);
Q_SIGNALS: // SIGNALS
    void authenticationError(uint error);
};

#endif
