/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c AccountAdaptor -a core/account_adaptor.h:core/account_adaptor.cpp org.saruneko.tori.account.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ACCOUNT_ADAPTOR_H_1358121595
#define ACCOUNT_ADAPTOR_H_1358121595

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.saruneko.tori.Account
 */
class AccountAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.saruneko.tori.Account")
    Q_CLASSINFO("D-Bus Introspection", ""
        "")
public:
    AccountAdaptor(QObject *parent);
    virtual ~AccountAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void authenticate();
    void isAuthenticated();
    void setPin(const QString &pin);
Q_SIGNALS: // SIGNALS
    void authenticated(bool authenticated, const QString &username);
    void authenticationError(uint error);
    void oauthPinUrl(const QString &pinUrl, const QString &username);
};

#endif
