/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c SessionInterface -p keyring/session.h:keyring/session.cpp -i secret.h org.freedesktop.secret.session.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "keyring/session.h"

/*
 * Implementation of interface class SessionInterface
 */

SessionInterface::SessionInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

SessionInterface::~SessionInterface()
{
}

