/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c Keyring -p keyring/keyring.h:keyring/keyring.cpp -i secret.h org.freedesktop.secrets.service.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef KEYRING_H_1353544999
#define KEYRING_H_1353544999

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "secret.h"

/*
 * Proxy class for interface org.freedesktop.secrets.service
 */
class Keyring: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.secrets.service"; }

public:
    Keyring(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~Keyring();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QDBusObjectPath, QDBusObjectPath> CreateCollection(const QVariantMap &properties, const QString &alias)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(properties) << QVariant::fromValue(alias);
        return asyncCallWithArgumentList(QLatin1String("CreateCollection"), argumentList);
    }
    inline QDBusReply<QDBusObjectPath> CreateCollection(const QVariantMap &properties, const QString &alias, QDBusObjectPath &prompt)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(properties) << QVariant::fromValue(alias);
        QDBusMessage reply = callWithArgumentList(QDBus::Block, QLatin1String("CreateCollection"), argumentList);
        if (reply.type() == QDBusMessage::ReplyMessage && reply.arguments().count() == 2) {
            prompt = qdbus_cast<QDBusObjectPath>(reply.arguments().at(1));
        }
        return reply;
    }

    inline QDBusPendingReply<QDBusVariant, QDBusObjectPath> OpenSession(const QString &algorithm, const QDBusVariant &input)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(algorithm) << QVariant::fromValue(input);
        return asyncCallWithArgumentList(QLatin1String("OpenSession"), argumentList);
    }
    inline QDBusReply<QDBusVariant> OpenSession(const QString &algorithm, const QDBusVariant &input, QDBusObjectPath &result)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(algorithm) << QVariant::fromValue(input);
        QDBusMessage reply = callWithArgumentList(QDBus::Block, QLatin1String("OpenSession"), argumentList);
        if (reply.type() == QDBusMessage::ReplyMessage && reply.arguments().count() == 2) {
            result = qdbus_cast<QDBusObjectPath>(reply.arguments().at(1));
        }
        return reply;
    }

    inline QDBusPendingReply<> SearchItems()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("SearchItems"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace freedesktop {
    namespace secrets {
      typedef ::Keyring service;
    }
  }
}
#endif
