#ifndef TORIDAEMONLIB_GLOBAL_H
#define TORIDAEMONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TORIDAEMONLIB_LIBRARY)
#  define TORIDAEMONLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TORIDAEMONLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TORIDAEMONLIB_GLOBAL_H
